### PR TITLE
Issue 167

### PR DESCRIPTION
**Pull request by jvieira88**
Fix issue 167 related to 12 bit packed format.

### CODE REVIEW

**Comment by jvieira88** [comment]
> Thank you for creating this pull request. By the way, why don't you refer to `alignment.unpacked_size`? Could you tell me the reason, please?

If I understood it correctly, `alignment.unpacked_size` would be used to calculate the size of the buffer already unpacked while I used `depth_in_byte` to calculate the size of the buffer as acquired from the camera and before unpacking. For example, in the 12 bit pixel case, `alignment.unpacked_size` would be 2 bytes while `depth_in_byte` would be 1.5 bytes. This is important since the actual size of the acquired buffer before unpacking is used as an argument to the `numpy.frombuffer`. If we were using the wrong size of the method would give an error.
`alignment.unpacked_size` would be more appropriate after expanding the buffer.

**Comment by kazunarikudo** [comment]
Thank you for your reply. Just a short question: Did not the original version work for ``Mono12Packed``?

**Comment by jvieira88** [comment]
> Thank you for your reply. Just a short question: Did not the original version work for `Mono12Packed`?

No. The original code would throw an exception in numpy.frombuffer which makes sense.
```
Exception has occurred: ValueError
buffer is smaller than requested size
```

**Comment by kazunarikudo** [comment]
Thank you. Okay, let me review the code by myself. There seems to be something inconsistent with my intention.

**Comment by jvieira88** [comment]
Hi @kazunarikudo. I can confirm the change is working, however if I may just suggest something, in `_to_np_array `method:
```
            try:
                w = self._buffer.width
            except NotImplementedException:
                w = self._node_map.Width.value
            try:
                h = self._buffer.height
            except NotImplementedException:
                h = self._node_map.Height.value
            nr_bytes = h * w
```
There are two try-except which I think could be made into one since if `self._buffer.width` is not implemented, then `self._buffer.height` won't be either. This is just to make the code cleaner.

I would suggest:
```
            try:
                w = self._buffer.width
                h = self._buffer.height
            except NotImplementedException:
                w = self._node_map.Width.value
                h = self._node_map.Height.value
            nr_bytes = h * w
```

Regards,
Joao

**Comment by kazunarikudo** [comment]
@jvieira88 Hi. Thank you for your comment.
> I would suggest:

I understand you want to make it compact/cleaner and you are seeing it from a logical point of view but it does not make sense to discard a valid one just because the other was unavailable.

At least the information about the GenTL Buffer module is supplied by the associate GenTL Producer. I'm seeing a benefit in prioritizing the data from GenTL Producers even if the code gets longer; this is not the topic about making code shorter or longer.

Does this make sense for you? I would like to leave it as is.

**Comment by jvieira88** [comment]
Sure, there's nothing wrong with that implementation and you know the code and implications better than I do! :)

**Comment by kazunarikudo** [comment]
Anyway, thank you for your comment. I appreciate that!

**Comment by kazunarikudo** [comment]
Closing, thank you for your contribution!

**Pull request closed without merging**
